name: Pull request or push to Dev Branch

on:
  push:
    branches:
      - dev

jobs:
  build:
    timeout-minutes: 30
    name: Deploy website
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Angular Deploy gh-pages Actions
      uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.3.1
      with:
        github_access_token: ${{ secrets.GH_TOKEN }} # see the Configuration section for how you can create secrets
        build_configuration: production # The build environment for the app. please look configurations in your angular.json
        base_href: / # make sure this corresponds to https://<your_username>.github.io/<base_href>/
        deploy_branch: master # The branch the action should deploy to.
        angular_dist_build_folder: dist/moni-roy.github.io
